#PATHS:
ddg2p_bed: "/Users/eg15/PycharmProjects/Indelible/data/DDG2P_18112014.bed"
ensembl_exons: "/Users/eg15/PycharmProjects/Indelible/data/protein_coding_ensembl_exons_gencode17.gff"
indelible_db: "/Users/eg15/PycharmProjects/Indelible/data/ddd4k_database.tsv"
random_forest_model: "/Users/eg15/PycharmProjects/Indelible/data/random_forest.pkl"
exac_constraint: "/Users/eg15/PycharmProjects/Indelible/data/cleaned_exac_with_pLI_march16_anno.txt"
hgnc_synonyms: "/Users/eg15/PycharmProjects/Indelible/data/hgnc_gene_synonyms.txt"
hgnc_file: "/Users/eg15/PycharmProjects/Indelible/data/hgnc_genes.tsv"

#BLASTPATHS:
blastdb: "/lustre/scratch119/humgen/projects/ddd/users/as33/resources/resources_striped/hs37d5.fa"
windowmaskerdb: "/lustre/scratch119/humgen/projects/ddd/users/as33/resources/resources_striped/wmasker.obinary"
repeatdb: "/lustre/scratch119/humgen/projects/ddd/users/as33/Indelible/repbase_fixed.fasta"

# PARAMETERS:
# -----------
# HC_THRESHOLD: Quality threshold at which to hard clip from the ends
# MINIMUM_LENGTH_SPLIT_READ: Minimum number of bases that need to be soft clipped for a read to be included
# MINIMUM_MAPQ: Minimum mapping quality for read to be included
# MININUM_AVERAGE_BASE_QUALITY_SR: Minimum average base quality for the soft-clipped segment for read to be included
# SHORT_SR_CUTOFF: The cutoff at which a soft-clipped segment is considered "short".
# MINIMUM_SR_COVERAGE: Minimum number of reads with soft-clipped segments at a position for that position to be outputted.
# SCORE_THRESHOLD: Minimum Indelible score to be considered for denovo calling
# SR_THRESHOLD: Maximum number of clipped reads in parental samples to be considered inherited
# COV_THRESHOLD: Minimum parental coverage to be able to call event as denovo
# WINDOW_SIZE: window around position to look for indels/clipped reads (window_size/2 to the left and to the right)
############

HC_THRESHOLD: 10
MINIMUM_LENGTH_SPLIT_READ: 5
MINIMUM_MAPQ: 5
MININUM_AVERAGE_BASE_QUALITY_SR: 10
SHORT_SR_CUTOFF: 10
MINIMUM_SR_COVERAGE: 3
SCORE_THRESHOLD: 0.6
SR_THRESHOLD: 3
COV_THRESHOLD: 9
WINDOW_SIZE: 5