#PATHS:
ddg2p_bed: "./data/DDG2P_18VI2018.bed"
ensembl_exons: "./data/hg19.ensemblv19.sorted.bed"
random_forest_model: "./data/random_forest.17IX2019.pkl"
exac_constraint: "./data/cleaned_exac_with_pLI_march16_anno.txt"
hgnc_synonyms: "./data/hgnc_gene_synonyms.txt"
hgnc_file: "./data/hgnc_genes.tsv"

#BLASTPATHS:
blastdb: "./data/hs37d5.fa"
windowmaskerdb: "./data/wmasker.obinary"
repeatdb: "./data/repeats.fasta"

# PARAMETERS:
# -----------
# HC_THRESHOLD: Quality threshold at which to hard clip from the ends
# MINIMUM_LENGTH_SPLIT_READ: Minimum number of bases that need to be soft clipped for a read to be included
# MINIMUM_MAPQ: Minimum mapping quality for read to be included
# MININUM_AVERAGE_BASE_QUALITY_SR: Minimum average base quality for the soft-clipped segment for read to be included
# SHORT_SR_CUTOFF: The cutoff at which a soft-clipped segment is considered "short".
# MINIMUM_SR_COVERAGE: Minimum number of reads with soft-clipped segments at a position for that position to be outputted.
# SCORE_THRESHOLD: Minimum Indelible score to be considered for denovo calling
# SR_THRESHOLD: Maximum number of clipped reads in parental samples to be considered inherited
# COV_THRESHOLD: Minimum parental coverage to be able to call event as denovo
# WINDOW_SIZE: window around position to look for indels/clipped reads (window_size/2 to the left and to the right)
############

HC_THRESHOLD: 10
MINIMUM_LENGTH_SPLIT_READ: 5
MINIMUM_MAPQ: 5
MININUM_AVERAGE_BASE_QUALITY_SR: 10
SHORT_SR_CUTOFF: 10
MINIMUM_SR_COVERAGE: 3
SCORE_THRESHOLD: 0.6
SR_THRESHOLD: 3
COV_THRESHOLD: 9
WINDOW_SIZE: 5
